# -*- coding: utf-8 -*-
{
    'name': 'vat module',
    'version': '12.0.1.0',
    'category': 'Studio',
    'description': u"""
This module has been generated by Odoo Studio.
It contains the apps created with Studio and the customizations of existing apps.
""",
    'author': 'proadvisory team',
    'depends': [
        'account',
        'base'
        
    ],
    'data': [
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_report.xml',
        'data/ir_actions_server.xml',
        'data/base_automation.xml',
    ],
  
}
